[profile.default]
src = "."
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"

# Solc settings
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = false

# EVM version
evm_version = "paris"

# Formatting
line_length = 100
tab_width = 4
bracket_spacing = true

# Gas reports
gas_reports = ["*"]

# FFI (Foreign Function Interface) - enable if needed for scripts
ffi = false

# Remappings (if using external libraries)
remappings = [
    "forge-std/=lib/forge-std/src/",
]

# RPC endpoints (can be overridden by environment variables)
[rpc_endpoints]
sepolia = "${RPC_URL}"
localhost = "http://localhost:8545"

# Etherscan configuration for contract verification
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"

[doc]
out = "docs"
title = "Age Verification Contracts"